name: chat_hub
description: "A real-time chat application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  flutter_riverpod: ^3.0.3
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.0
  cherry_toast: ^1.13.0
  intl: ^0.20.2
  uuid: ^4.5.2
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  zego_uikit_prebuilt_call: ^4.22.2
  permission_handler: ^12.0.1
  zego_uikit_signaling_plugin: ^2.8.19
  zego_uikit: ^2.28.35
  provider: ^6.1.5+1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_contacts: ^1.1.9+2
  emoji_picker_flutter: ^4.4.0
  flutter_svg: ^2.2.3
  flutter_animate: ^4.5.2
  firebase_messaging: ^16.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ✅ App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

# ✅ App Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#692960"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
